services:
  web:
    image: "spring-introduction"
    ports:
      - 9090:9090
      - 9091:9091
    depends_on:
      - db1
      - db2
    environment:
      DATABASE_URL: jdbc:postgresql://spring-introduction-postgres:5432/springintroduction

  db1:
    container_name: spring-introduction-postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: springintroduction

  db2:
    container_name: spring-introduction-minio
    image: quay.io/minio/minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ..\minio\data:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command:
      - server
      - --console-address
      - ":9001"
      - /data