services:
  web:
    image: "spring-introduction"
    ports:
      - 9090:9090
      - 9091:9091
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:postgresql://spring-introduction-postgres:5432/springintroduction


  db:
    container_name: spring-introduction-postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: springintroduction