server:
  ssl:
    key-store-type: "PKCS12"
    key-alias: "springboot"
    key-store-password: "password"
    key-store: "classpath:keystore/springboot.p12"
  port: 9091
  http:
    port: 9090
  servlet:
    encoding:
      charset: "UTF-8"
      force: false

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/springintroduction}
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

configuration:
  cron:
    schedule: "0 0 * * * *"

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  username: root
  password: password