server:
  ssl:
    enabled: false
  http:
    port: 9090

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/springintroduction}
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

configuration:
  cron:
    schedule: "0 0 * * * *"

handler:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  username: root
  password: password