name: Automatic test of app
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Test of app
      run: mvn -B clean test
