name: Automatic test of app
on:
  push:
    paths:
      - '*.java'
  workflow_dispatch:
      
jobs:
  test_app:
    runs-on: ubuntu-latest
                    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository  # Specify the path to your Maven dependencies
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        
    - name: Test of app
      run: mvn -B clean test
